language: node_js
dist: trusty
sudo: required
node_js: stable

env:
  matrix:
  - PATH=$HOME/purescript:$PATH

install:
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/v0.13.0/linux64.tar.gz
- tar -xvf $HOME/purescript.tar.gz -C $HOME/
- chmod a+x $HOME/purescript
- npm install -g bower pulp@13.0.0 spago@0.8.3
- spago install
- bower install

script:
- export VERSION=branch-job-$TRAVIS_JOB_NUMBER
- if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then export VERSION=pull-request-job-$TRAVIS_JOB_NUMBER;
  fi
- if [[ "$TRAVIS_TAG" != "" ]]; then export VERSION=$TRAVIS_TAG; fi
- spago build
- spago test
- rm -rf .spago output
- pulp build
